// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMY6XlPkCn5F-nzZ7NaiJyRQPLbkGKtiI',
    appId: '1:965601252516:web:753844025f81a5afebc231',
    messagingSenderId: '965601252516',
    projectId: 'petparadise-6ba94',
    authDomain: 'petparadise-6ba94.firebaseapp.com',
    storageBucket: 'petparadise-6ba94.firebasestorage.app',
    measurementId: 'G-F5WJJEFQDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzOxHpqx0NTh06q7ASFJ_gVFA8oG4x_Kw',
    appId: '1:965601252516:android:dd02d0dffa7a10a2ebc231',
    messagingSenderId: '965601252516',
    projectId: 'petparadise-6ba94',
    storageBucket: 'petparadise-6ba94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX4Y4i5NmrZ-rjjXgV_ZFVcpfGX1bXi5E',
    appId: '1:965601252516:ios:4f6d852244c89fa2ebc231',
    messagingSenderId: '965601252516',
    projectId: 'petparadise-6ba94',
    storageBucket: 'petparadise-6ba94.firebasestorage.app',
    iosBundleId: 'com.nurhakiki.petParadise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX4Y4i5NmrZ-rjjXgV_ZFVcpfGX1bXi5E',
    appId: '1:965601252516:ios:4f6d852244c89fa2ebc231',
    messagingSenderId: '965601252516',
    projectId: 'petparadise-6ba94',
    storageBucket: 'petparadise-6ba94.firebasestorage.app',
    iosBundleId: 'com.nurhakiki.petParadise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMY6XlPkCn5F-nzZ7NaiJyRQPLbkGKtiI',
    appId: '1:965601252516:web:f2072b430f1f775bebc231',
    messagingSenderId: '965601252516',
    projectId: 'petparadise-6ba94',
    authDomain: 'petparadise-6ba94.firebaseapp.com',
    storageBucket: 'petparadise-6ba94.firebasestorage.app',
    measurementId: 'G-JM1ZC2N9EX',
  );
}
